export const metadata = { title: 'Terms of Service' }

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-sm text-gray-400">Last updated: June 2026</p>

      <p>
        Welcome to ComplyFlow ("ComplyFlow," "we," "us," or "our"). These Terms of Service ("Terms") govern your
        access to and use of the ComplyFlow website, dashboard, and related services (collectively, the "Service").
        By creating an account or using the Service, you agree to be bound by these Terms.
      </p>

      <h2>1. Important Notice: Not a Law Firm or CPA Firm</h2>
      <p>
        ComplyFlow is a software and information platform only. ComplyFlow is NOT a law firm, NOT a CPA firm, and
        NOT a government agency. We do not provide legal, tax, or financial advice. We do not prepare or file
        documents with any government agency on your behalf, and we do not guarantee any government approval or
        filing outcome. Nothing on this platform should be construed as legal, tax, or financial advice. You should
        consult a licensed attorney, accountant, or other qualified professional regarding your specific situation.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 18 years old and capable of forming a binding contract to use the Service. By using
        the Service, you represent that you meet these requirements.
      </p>

      <h2>3. Account Registration</h2>
      <p>
        You are responsible for maintaining the confidentiality of your account credentials and for all activity
        that occurs under your account. You agree to provide accurate and complete information during registration
        and to keep that information up to date.
      </p>

      <h2>4. Subscription Plans and Billing</h2>
      <p>
        ComplyFlow offers a free tier and paid subscription plans billed monthly or annually through our payment
        processor, Stripe. By subscribing to a paid plan, you authorize us to charge your payment method on a
        recurring basis until you cancel. Paid plans may include a free trial period; if you do not cancel before
        the trial ends, you will be charged the applicable subscription fee.
      </p>

      <h2>5. Use of the Document Vault</h2>
      <p>
        You retain ownership of all documents you upload to the Service. You are solely responsible for the
        accuracy, legality, and content of any documents you upload. ComplyFlow does not review, verify, or
        guarantee the accuracy of uploaded documents.
      </p>

      <h2>6. AI Assistant</h2>
      <p>
        The Service includes an AI-powered assistant feature for general informational purposes. The AI Assistant
        does not provide legal, tax, or financial advice and should not be relied upon as a substitute for
        professional counsel. Responses generated by the AI Assistant may contain errors or inaccuracies.
      </p>

      <h2>7. Prohibited Conduct</h2>
      <p>
        You agree not to misuse the Service, including by attempting to gain unauthorized access to other accounts
        or systems, uploading malicious content, or using the Service for any unlawful purpose.
      </p>

      <h2>8. Termination</h2>
      <p>
        We reserve the right to suspend or terminate your account if you violate these Terms. You may cancel your
        subscription or delete your account at any time through your account settings.
      </p>

      <h2>9. Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO
        NOT WARRANT THAT THE SERVICE WILL BE ERROR-FREE, UNINTERRUPTED, OR THAT ANY DEADLINE TRACKING OR COMPLIANCE
        INFORMATION WILL BE ACCURATE OR COMPLETE FOR YOUR SPECIFIC JURISDICTION OR BUSINESS TYPE.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPLYFLOW SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
        SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION ANY MISSED DEADLINE, GOVERNMENT
        PENALTY, OR LOST BUSINESS OPPORTUNITY, ARISING FROM YOUR USE OF THE SERVICE.
      </p>

      <h2>11. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the Service after changes are posted
        constitutes acceptance of the revised Terms.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these Terms can be directed to support@complyflow.com.
      </p>
    </>
  )
}
